[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
verify = "5Y61S87J7uvrcqCaHt5Svii3pLA3XyYUZpXzM3Qkuyyb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/fZRoLpYJI33SdXL-FpL7kGy3mMiy0i8a"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
